spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: ce076c5a-380f-443c-b65a-b40fd2819070
        cluster-name: BJ
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
        client-ip: 127.0.0.1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定topic
          destination: add-bonus
        my-output:
          destination: stream-my-topic

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

#饥饿加载,多个client逗号分隔
ribbon:
  eager-load:
    enabled: true
    client: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      #想要调用的微服务的名称/全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itmuch.contentcenter.interceptor.TokenRelayRequestIntecepor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

#  okhttp:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
resttemplate:
  sentinel:
    # 设置成false,表示关闭@SentinelRestTemplate注解
    enabled: false

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 小坑：必须指定group
    group: test-group