spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: ce076c5a-380f-443c-b65a-b40fd2819070
        cluster-name: BJ
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
#      datasource:
#        # 名称随意
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            # 规则类型，取值见：
#            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
        client-ip: 127.0.0.1
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010


#负载均衡配置
#细粒度属性配置
#user-center:
#  ribbon:
#    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#饥饿加载,多个client逗号分隔
ribbon:
  eager-load:
    enabled: true
    client: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      #想要调用的微服务的名称/全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

#  okhttp:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate注解
    enabled: false
#ahas.namespace: default
#project.name: content-center
#ahas.license: a791265542e74f6ead7eae5d804c2c84